# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_link_source',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
