# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_i_link_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_conf_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='i_conf_2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
