# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170701_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='i_conf_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='i_conf_2',
        ),
    ]
