# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170728_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_subsystem',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
