# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item_i_subsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='en',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Enviroment'),
            preserve_default=False,
        ),
    ]
