# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170728_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='i_description',
        ),
        migrations.AddField(
            model_name='item',
            name='i_processName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Enviroment',
        ),
    ]
